### ISSUE TITLE
Rust roadmap

### ISSUE THREAD

**Issue by TAINCER** [NimbusPulse/sdk#4]
# Roadmap for rust impl:

- [x] Get all Servers
- [x] Get Server by ID
- [x] Create Server
- [x] Delete Server
- [x] Start Server
- [x] Stop Server
- [x] Add Missions
- [x] Delete Missions
- [x] Select Mission
- [x] Start Mission
- [x] Pause Server
- [x] Resume Server
- [x] Get Server Runtime Response
- [x] Get Server Runtime
- [x] Get Server Resources

**Comment by Weissstreifen** [comment]
lgtm
