### ISSUE TITLE
JS/TS roadmap

### ISSUE THREAD

**Issue by TAINCER** [NimbusPulse/sdk#5]
# Roadmap for js/ts impl:

- [x] Get all Servers
- [x] Get Server by ID
- [x] Create Server
- [x] Delete Server
- [x] Start Server
- [x] Stop Server
- [x] Add Missions
- [x] Delete Missions
- [ ] Select Mission
- [ ] Start Mission
- [ ] Pause Server
- [ ] Resume Server
- [ ] Get Server Runtime Response
- [ ] Get Server Runtime
- [ ] Get Server Resources
